# Inception Project: Docker Compose Configuration

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    # We now pass the path to the secret files via environment variables.
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      WORDPRESS_DATABASE_PASSWORD_FILE: /run/secrets/db_password
    # This makes the secrets available inside the container at the specified paths.
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      # The healthcheck now reads the password from the secret file.
      test: ["CMD-SHELL", "mariadb-admin ping --socket=/run/mysqld/mysqld.sock -u root -p$$(cat $$MYSQL_ROOT_PASSWORD_FILE)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    # Pass the paths to the secret files to the WordPress container.
    environment:
      WORDPRESS_DATABASE_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WORDPRESS_USER_PASSWORD_FILE: /run/secrets/wp_user_password
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    depends_on:
      - wordpress
    restart: on-failure

networks:
  inception:
    driver: bridge
    name: inception_network

volumes:
  mariadb_data:
  wordpress_data:

# Top-level secrets block tells Docker where to find the secret files on the host.
secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt