services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      WORDPRESS_DATABASE_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping --socket=/run/mysqld/mysqld.sock -u root -p$$(cat $$MYSQL_ROOT_PASSWORD_FILE)"]
      interval: 10s
      timeout: 5s
      retries: 5
      # Increase the grace period to 3 minutes to allow for slow startup.
      start_period: 180s

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    environment:
      WORDPRESS_DATABASE_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WORDPRESS_USER_PASSWORD_FILE: /run/secrets/wp_user_password
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    # This is the correct syntax for waiting on the healthcheck.
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    # This is the simple dependency form, which is sufficient here.
    depends_on:
      - wordpress
    restart: on-failure

networks:
  inception:
    driver: bridge
    name: inception_network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rkhakimu/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rkhakimu/data/wordpress


secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt
