services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    restart: always
    volumes:
      - /home/rkhakimu/data/mariadb:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - /home/rkhakimu/data/wordpress:/var/www/html
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://nginx || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/rkhakimu/data/wordpress:/var/www/html:ro
    networks:
      - inception

networks:
  inception:
    name: inception_network
    driver: bridge
